### ISSUE TITLE
Lag switiching "windows"

### ISSUE THREAD

**Issue by no112358** [nknorg/nMobile#113]
Hello

I experience lag switching between D-chat, Account and Settings in the app on my OnePlus 5, Nexus 4 but NOT on an iPhone 6. Either by clicking or swiping trough the "windows".

Should be smooth as on the iPhone

Happens on version:
1.0.5
1.0.4

https://youtu.be/IVargwEb3ls

**Comment by Rebloom** [comment]
Copy that, we will check the problem as soon as possible

**Comment by Rebloom** [comment]
This issue might be flutter engine cross platform performance difference.
Busy debug on loss of message.
I am sorry for not respond for a long time.
This issue should be marked as level3.

**Comment by no112358** [comment]
Fixed in 1.1.0
