### ISSUE TITLE
Bug: backing up / exporting account

### ISSUE THREAD

**Issue by no112358** [nknorg/nMobile#114]
I create a new account and when the "Not backed up yet" appears I click it, I input my fingerprint and nothing happens. If I cancel the fingerprint and enter the password manualy, then it works and I can export the account info. Same happens, if you're in your account and click "export account".

Both should work on fingerprint and password.

Happens on:
OnePlus 5 nMobile 1.0.5
Nexus 4 can't test, no fingerprint, password works

**Comment by Rebloom** [comment]
This bug marked as level2, I will put it on the feature list and should be fixed as 1.1.x Version.

**Comment by no112358** [comment]
Fixed in 1.1.0
