### ISSUE TITLE
Dchat changing the nickname

### ISSUE THREAD

**Issue by no112358** [nknorg/nMobile#115]
Locally changing the nickname of a contact.

By clicking  on "nickname" in contact page and editing the contact name succesfully, should also change the text on the contact page.

Currently the "Nickname" text stays the same 6 characters of your Dchat ID.

It should reflect the change.

**Comment by Rebloom** [comment]
Thanks for the detail of changing the Nickname.
This bug marked as level2 and it should be fixed in 1.1.x Version.

**Comment by no112358** [comment]
Fixed in 1.1.0
