### ISSUE TITLE
nMobile TouchID / password verification

### ISSUE THREAD

**Issue by no112358** [nknorg/nMobile#116]
Currently theres a few bugs with it.

It asks for password immediately after you leave the app and switch back, which is safe but really annoying, there should be a setting to increase the time or just increase it.

This also happens when you try to send a picture and you enter the gallery app or camera app to select or take a picture. The password / touchID should not be required at this point.

**Comment by Rebloom** [comment]
We have a discussion on the safe protection, and we intend to use touchId(or other biometrics) for safety use,
I think a touchId switch on the password dialog and you can switch it off. How about this?
The bug was confirmed and should be fixed in 1.1.0 Version.

**Comment by no112358** [comment]
> 
> 
> We have a discussion on the safe protection, and we intend to use touchId(or other biometrics) for safety use,
> I think a touchId switch on the password dialog and you can switch it off. How about this?
> The bug was confirmed and should be fixed in 1.1.0 Version.

The problem is that, when you switch apps nMobile relocks immediately and requests a password again. That is anoyoing, a feature where you can select a relock timer would be nice, if you know what I mean. Even my banking app doesn't relock immediately by default

**Comment by no112358** [comment]
Fixed in 1.1.0
