### ISSUE TITLE
Sending pictures to iOS device fails

### ISSUE THREAD

**Issue by no112358** [nknorg/nMobile#117]
I sent pictures from my OnePlus 5 to a iPhone 6 and pictures never arrive, they stay grayed out. Text works fine. Sent both ways and the pictures don't arrive. Works fine between two android devices. Pictures haven't arrived or been sent, even after many hours.

Warrants further investigation.

1.0.5 on both devices

**Comment by Rebloom** [comment]
The picture should have been sent,And I guess it would be a delay on our node clients.Or some issue we have not confirmed.
We are focusing on this problem.
It would be relieve on 1.1.0 Version.

**Comment by no112358** [comment]
Fixed in 1.1.0
