### ISSUE TITLE
Backup / Exporting account info 1.0.5

### ISSUE THREAD

**Issue by no112358** [nknorg/nMobile#118]
bug 1:
For some reason I can't export an ERC-20 account info on latest test account I set up. "Account password or keystore file is wrong". Can't open it with TouchID also because of bug where TouchID bug for ERC20 accounts.

I entered the same password I used to create the account. I tried several new accounts to check if I somehow failed with password setup. I didn't.

https://youtu.be/C7s5sclPeqk

bug 2:
when it does work, the account info is not displayed fully in some cases, too much text in the field. Change the text fields to dynamic size. On ERC-20 the seed is longer and doesn't display fully.

**Comment by Rebloom** [comment]
Thanks for the detail, bug1 will be fixed in Version1.1.0
bug2 is a display issue, it should be fixed in Version1.1.x

**Comment by no112358** [comment]
Fixed in 1.1.0
